# Generated by Django 3.2.9 on 2022-07-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pupil',
            new_name='Student',
        ),
    ]
